config/routes.rb
Rails.application.routes.draw do
  get 'pet_reviews/new'
  devise_for :users do
    resources :pet_reviews, only: [:create]
  end
  root to: "pages#home"
  get "/profile", to: "users#profile"
  get "/users/:id", to: "users#show", as: :user
  resources :pets do
    resources :pet_reviews, only: [:create]
    resources :bookings, only:[:create]
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :pet_reviews, dependent: :destroy
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :name, :species, :photo, presence: true

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/pet_review.rb
class PetReview < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  validates :content, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :pets, dependent: :destroy
  has_many :bookings
  has_many :pet_reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end

  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @pet = Pet.find(params[:pet_id])
    authorize @pet
    if @pet.user == current_user
      flash.alert = "Cannot book your own pet."
      redirect_to pet_path(@pet)
    else
      @booking = Booking.new(booking_params)
      @booking.pet = @pet
      @booking.user = current_user
      redirect_to profile_path if @booking.save
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :pet_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only:[:home]
  def home

    if current_user.present?
      all_pet = Pet.all
      @pets = []
      all_pet.each do |pet|
        @pets << pet if pet.user_id != current_user.id
        end
      @pets
    else
      @pets = Pet.all
    end

    if current_user.present?
      @users = User.where.not(id: current_user.id)
    else
      @users = User.all
    end

    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {user: user})
      }
    end

  end
end

app/controllers/pet_reviews_controller.rb
class PetReviewsController < ApplicationController
  def create
    @pet = Pet.find(params[:pet_id])
    @pet_review = PetReview.new(review_params)
    @pet_review.pet = @pet
    @pet_review.user = current_user
    authorize @pet_review
    respond_to do |format|
      if @pet_review.save
        format.html { redirect_to pet_path(@pet) }
        format.json
      else
        format.html { render 'pets/show', status: :unprocessable_entity }
        format.json
      end
    end
  end

  def review_params
    params.require(:pet_review).permit(:content, :rating, :pet_id, :user_id)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:search, :show]
  def show
    @pet = Pet.find(params[:id])
    @pet_review = PetReview.new
    @booking = Booking.new
    @markers = @pet.user.geocode.map do
      {
        lat: @pet.user.latitude,
        lng: @pet.user.longitude
      }
    end
    authorize @pet
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    authorize @pet
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
    @pet = Pet.find(params[:id])
    authorize @pet
  end

  def update
    @pet = Pet.find(params[:id])
    authorize @pet
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    authorize @pet
    if @pet.bookings.exists?
      flash.alert = "Booking exist. Can't be deleted."
      redirect_to pet_path(@pet)
    else
      @pet.destroy
      redirect_to profile_path, status: :see_other
    end
  end

  def search
    @pets = Pet.where('lower(species) = ?', params[:query].downcase)
    @search_query = params[:query]
    @result_count = @pets.count
    authorize @pets
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :age, :species, :available, :photo, :description, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    all_pets = Pet.all
    @pets = []
    all_pets.each do |pet|
      @pets << pet if pet.user_id == current_user.id
    end
    @pets
    authorize current_user
  end

  def show
    @user = User.find(params[:id])
    @pets = @user.pets
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPet</title>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/_info_window.html.erb
<h2><i class="fa-solid fa-user text-success text-decoration-none mx-2"></i><%= link_to user.first_name, user_path(user), class:"text-success text-decoration-none" %></h2>
<p><%= user.address %></p>

app/views/pages/home.html.erb
<div class="home" data-controller="map"
data-map-markers-value="<%= @markers.to_json %>"
data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
data-map-has-popup-value= "true">

  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1529330250279-95a914498cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTh8fGRvZyUyMGZvciUyMGElMjB3YWxrfGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60);">
    <div class="container">
      <h1>Rent a Pet <strong> brings all creatures,</strong> great and small together</strong></h1>
      <p>To buddy up - Worldwide, wherever you stray.</p>
      <div>
        <% if !user_signed_in? %>
          <%= link_to "Sign_up", new_user_registration_path, class:"btn btn-success text-white"%>
        <%end%>
        <button class="btn btn-success text-white mx-3 sora" data-action="click->map#change" >
          <div data-map-target="buttonmap">Show Map <i class="fa-solid fa-map-location-dot"></i></div>
          <div data-map-target="buttonlist" class="d-none">Show List <i class="fa-solid fa-list-ul"></i></div>
        </button>
      </div>
    </div>
  </div>

  <div data-map-target='list' class="my-5">
    <div class="cards">
      <% @pets.each do |pet| %>
      <div class="card-category  d-flex flex-column" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path pet.photo.key, height: 300, crop: :fill, effect: :improve %>')">
        <%= link_to pet.name.upcase, pet_path(pet) %>
        <span> Age: <%= pet.age %></span>
      </div>
      <% end %>
    </div>
  </div>

  <div data-map-target='map' class="d-none my-5">

    <div style="width: 100%; height: 500px;"
      data-map-target="container"
      id="map">
    </div>

  </div>



</div>

app/views/pet_reviews/_form.html.erb
<%= simple_form_for([pet, pet_review], data: {insert_in_list_target: 'form', action: "submit->insert-in-list#send"}) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 1..5, prompt: "Select rating" %>
  <%= f.submit "Submit", class: "btn btn-success" %>
<% end %>

app/views/pets/_pet_review.html.erb
<li class="py-2">
  <strong><%= pet_review.user.first_name %>:  </strong><%= pet_review.content %>
  <% pet_review.rating.times do %>
    <i class="fa-solid fa-star" style="color: #009500;"></i>
  <% end %>
</li>

app/views/pets/edit.html.erb
<div class="d-flex justify-content-center">
<div class="create-edit-form">
  <%= simple_form_for @pet do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :species %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.input :available, as: :boolean, collection: [[true, 'Available'], [false, 'Not available']] %>
    <%= f.submit "Edit the pet!", class: "btn btn-success" %>
  <% end %>
</div>
</div>

app/views/pets/new.html.erb
<div class="d-flex justify-content-center">

<div class="create-edit-form">
  <%= simple_form_for @pet do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :species %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.input :available, as: :boolean, collection: [[true, 'Available'], [false, 'Not available']] %>
    <%= f.submit "Create new pet!", class: "btn btn-success" %>
  <% end %>
<div>

</div>

app/views/pets/search.html.erb
<h5 class="search-result-title">Showing <%= @result_count %> result(s)
 for: <b><%= @search_query %></b></h5>
<div class="cards px-5">
  <% @pets.each do |pet| %>
  <div class="card-category d-flex flex-column" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path pet.photo.key, height: 300, crop: :fill, effect: :improve %>')">
    <%= link_to pet.name.upcase, pet_path(pet)%>
    <span> Age: <%= pet.age %></span>
  </div>
  <% end %>
</div>

app/views/pets/show.html.erb
<div class="container-show">

 <div class="map" style="width: 400px; height: 300px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    data-map-target="container"
    data-map-has-popup-value= "false" >
  </div>

  <div class="pet-image">
    <%= cl_image_tag @pet.photo.key, height: 300, width: 400, crop: :fill %>
  </div>

</div>



<div class="container">
  <div class="pet-name">
    <h1><%= @pet.name %></h1>
  </div>

  <div class="edit">
    <% if policy(@pet).edit? %>
      <%= link_to edit_pet_path(@pet) do %>
        <i class="fa-solid fa-pen-to-square" style="color: #009500;"></i>
      <% end %>
      <%= link_to pet_path(@pet), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  do %>
        <i class="fa-solid fa-trash-can" style="color: #009500;"></i>
      <% end %>
    <% end %>
  </div>
  <div class="pet-owner">
   <h2> <%= @pet.user.first_name %>
   <i class="fa-regular fa-user"></i></h2>
  </div>
  <div class="owner-address">
   <p> <%= @pet.user.address %></p>
   <i class="fa-solid fa-location-dot"></i>
  </div>
  <p class="dropdown"><%= @pet.description %></p>
</div>






<% if user_signed_in? %>
  <div class="accordion dropdown" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Reviews <i class="fa-solid fa-comment px-2"></i>
        </button>
      </h2>



      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">

          <div class="py-5" data-controller='insert-in-list'>

            <% if current_user != @pet.user %>
              <div class="mb-4">
                <h3>New Review</h3>
                <%= render 'pet_reviews/form', pet: @pet, pet_review: @pet_review %>
              </div>
            <% end %>

            <h3>All Reviews</h3>
            <ul class="list-unstyled"  data-insert-in-list-target='items'>
              <% @pet.pet_reviews.order(created_at: :desc).each do |pet_review| %>
                  <%= render 'pets/pet_review', pet_review: pet_review %>
              <% end %>
            </ul>

          </div>

        </div>
      </div>
    </div>
  </div>
<% end %>







<div class="d-flex justify-content-center mt-5">
  <div class="booking-form">
    <% if user_signed_in? %>
      <% if current_user != @pet.user %>
        <h1>New Booking</h1>
        <%= simple_form_for [@pet, @booking],  data: { controller: 'flatpickr', unavailable_dates: @pet.unavailable_dates.to_json } do |f| %>
          <%= f.input :start_date, as: :string, input_html: { type: 'date', data: { flatpickr_target: "startDate" }, class: "datepicker" } %>
          <%= f.input :end_date, as: :string, input_html: { type: 'date', data: { flatpickr_target: "endDate" }, class: "datepicker" } %>
          <%= f.submit "Book it!", class:"btn btn-success" %>
        <% end %>
      <% end %>
    <% else %>
      <div class="alert alert-dismissible fade show">
        <strong><i class="fa-solid fa-triangle-exclamation"></i></strong> You should log in to book it.
      </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="row container-fluid">
    <div class="col-6">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto align-items-center">
        <li class="nav-item active">
          <div class="nav-link-wrapper">
            <i class="fa-solid fa-house"></i>
            <%= link_to "Home", root_path, class: "nav-link" %>
          </div>
        </li>
     <% if user_signed_in? %>
      <li class="nav-item active">
       <div class="nav-link-wrapper">
        <i class="fa-solid fa-user"></i>
        <%= link_to "My page", profile_path, class: "nav-link" %>
       </div>
      </li>
      <li class="nav-item">
       <div class="nav-link-wrapper">
        <i class="fa-solid fa-paw"></i>
        <%= link_to "Add a pet", new_pet_path, class: "nav-link" %>
       </div>
      </li>
      <li class="nav-item">
       <div class="nav-link-wrapper">
        <i class="fa-solid fa-right-from-bracket"></i>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
       </div>
      </li>
          <% else %>
          <li class="nav-item">
            <div class="nav-link-wrapper">
             <i class="fa-solid fa-right-to-bracket"></i>
             <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-6">
      <div class="pets-search-bar">
        <%= form_with url: search_pets_path, method: :get do |form| %>
          <div class="input-group mb-3">
            <%= form.text_field :query, placeholder: "Enter pet specie e.g Dog", class: "form-control" %>
            <%= form.submit "Search", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="user-info-profile">
  <h2><%= "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize}" %></h2>
  <h5><%= current_user.email %></h5>
  <p><%= current_user.address %></p>
</div>

<div class = "container-profile">
  <div class="current-pets">
    <h2 class="booking-text">Your current pets</h2>
     <% @pets.each do |pet| %>
        <ul class="list-unstyled text-decoration-none">
          <li>
            <div class="cards">
              <div class="card-product">
                <%= cl_image_tag pet.photo.key, height: 300, width: 400, crop: :fill %>
                <div class="card-product-infos">
                  <h2><%= link_to pet.name, pet_path(pet), class:"text-decoration-none" %></h2>
                  <p>Age <%= pet.age %></p>
                  <% if pet.available %>
                    <i class="fa-solid fa-check"></i>
                  <% else %>
                    <i class="fa-solid fa-xmark"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        </ul>
      <% end %>

  </div>

  <div class="current-booking">
    <h2 class="booking-text">Your current booking</h2>
    <% current_user.bookings.each do |booking| %>
      <ul class="list-unstyled text-decoration-none">

        <li>
          <div class="card-product">
            <%= cl_image_tag booking.pet.photo.key, height: 300, width: 400, crop: :fill %>
            <div class="card-product-infos">
              <h2><%= link_to booking.pet.name, pet_path(booking.pet), class:"text-decoration-none" %></h2>
              <p>Age <%= booking.pet.age %></p>
            </div>
          </div>
        </li>

      </ul>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="current-pets">
    <h2 class="booking-text"><%= @user.first_name %>'s current pets</h2>
     <% @pets.each do |pet| %>
        <ul class="list-unstyled text-decoration-none">
          <li>
            <div class="cards">
              <div class="card-product">
                <%= cl_image_tag pet.photo.key, height: 300, width: 400, crop: :fill %>
                <div class="card-product-infos">
                  <h2><%= link_to pet.name, pet_path(pet), class:"text-decoration-none" %></h2>
                  <p>Age <%= pet.age %></p>
                  <% if pet.available %>
                    <i class="fa-solid fa-check"></i>
                  <% else %>
                    <i class="fa-solid fa-xmark"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        </ul>
      <% end %>
  </div>
</div>